# name: Build on push to aws

# on: 
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps: 
#       - name: checkout repo
#         uses: actions/checkout@v3

#       - name: setup dotnet
#         uses: actions/setup-dotnet@v3
#         with: 
#           dotnet-version: '8.0'

#       - name: build project
#         run: dotnet restore; dotnet publish -o site --configuration Release --runtime linux-x64

#       - name: check site directory contents
#         run: ls -la site

#       - name: create zip package
#         run: cd site; zip -r ../site.zip *

#       - name: Deploy to AWS EB
#         uses: einaregilsson/beanstalk-deploy@v21
#         with:
#           aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           application_name: Vigenere Web App
#           environment_name: VigenereWebApp-env-1
#           version_label: ${{ github.run_id }}
#           region: eu-north-1
#           deployment_package: site.zip
